##############################################
#     Make file of SONYIMX219 camera sensor
##############################################

EXTRA_CFLAGS += -Idrivers/huawei/drivers/camera/sonyimx219/
#EXTRA_CFLAGS += -fno-pic
ccflags-$(CONFIG_HI6620_CAMERA_SONYIMX219) += -DIMX219_OTP
obj-$(CONFIG_HI6620_CAMERA_SONYIMX219) += sonyimx219.o

#################### END #####################
