/* This file should be auto-generated by tool, please don't manully modify it.*/
#include "hisi_battery_data_default.c"
#include "hisi_battery_data_sony_2000.c"
#include "hisi_battery_data_sony_2460.c"
#include "hisi_battery_data_atl_3900.c"
#include "hisi_battery_data_lishen_2000.c"
#include "hisi_battery_data_lishen_2460.c"
#include "hisi_battery_data_guangyu_4000.c"
#include "hisi_battery_data_sunwoda_2460.c"
#include "hisi_battery_data_Default_2300.c"
#include "hisi_battery_data_Lishen_2300.c"
#include "hisi_battery_data_Scud_2300.c"
#include "hisi_battery_data_Sunwoda_2300.c"

static struct hisi_smartstar_coul_battery_data *bat_data_array_0[BAT_DATA_ARRAR_SIZE] = {
    &sony_2000_battery_data,    // must start with default data
    &lishen_2000_battery_data,
    0,    // must end with 0
};

static struct hisi_smartstar_coul_battery_data *bat_data_array_1[BAT_DATA_ARRAR_SIZE] = {
    &atl_3900_battery_data,    // must start with default data
    &guangyu_4000_battery_data,
    0,    // must end with 0
};

static struct hisi_smartstar_coul_battery_data *bat_data_array_2[BAT_DATA_ARRAR_SIZE] = {
    &lishen_2460_battery_data,    // must start with default data
    &sunwoda_2460_battery_data,
	&sony_2460_battery_data,
    0,    // must end with 0
};

static struct hisi_smartstar_coul_battery_data *bat_data_array_3[BAT_DATA_ARRAR_SIZE] = {
    &Default_2300_battery_data,   
    &Lishen_2300_battery_data,
    &Scud_2300_battery_data,
    &Sunwoda_2300_battery_data,
    0,    // must end with 0
};

static p_bat_data_array bat_data_array_all[] = {
    bat_data_array_0,  // SS_PRODUCT_INDEX_0
    bat_data_array_1,  // SS_PRODUCT_INDEX_1
    bat_data_array_2,  // SS_PRODUCT_INDEX_2
    bat_data_array_3,
};

