##############################################
#     Make file of OV8858 camera sensor
##############################################

EXTRA_CFLAGS += -Idrivers/huawei/drivers/camera/ov8858/
#EXTRA_CFLAGS += -fno-pic
ccflags-$(CONFIG_HI6620_CAMERA_OV8858) += -DOV8858_OTP
obj-$(CONFIG_HI6620_CAMERA_OV8858) += ov8858.o

#################### END #####################
