# 
# Makefile for hisilicon K3 soc camera v4l2 driver
# Author: j00140427
#
EXTRA_CFLAGS += -Idrivers/media/video/hi6620/vpp

obj-$(CONFIG_VIDEO_HI6620_VPP) = vpp.o
vpp-objs=vpp_drv.o vpp_inter.o vpp_hal.o

